# SpamDetector

Hier wollen wir den Algo Bag of Words schrittweise nachbauen, um damit dann die Worte in den Zeilen durch
Zahlen dargestellt zu bekommen, denn nur so können sie automatisiert verarbeitet werden.

In [7]:
import pandas as pd

In [8]:
df = pd.read_table('smsspamcollection/SMSSpamCollection',
                   sep='\t', 
                   header=None, 
                   names=['label', 'sms_message'])
#Die ersten 5 Elemente ausgeben
print(df.head())

  label                                        sms_message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...


In [9]:
#Die Werte spam und ham auf 0 oder 1 mappen, da der weitere Algorithmus nur Zahlen verarbeiten kann
df['label'] = df.label.map({'ham':0, 'spam':1})

#Die Form der Liste ausgeben
print(df.shape)

#Erneut die ersten 10 (nun modifizierten) Elemente ausgeben
print(df.head())

(5572, 2)
   label                                        sms_message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...


In [10]:
#Uebung - convert to lower case
print("Convert to lower case")
documents = ['Hello, how are you!',
             'Win money, win from home.',
             'Call me now.',
             'Hello, Call hello you tomorrow?']
print(documents)
lower_case_documents = []
for i in documents:
    lower_case_documents.append(i.lower())
print(lower_case_documents)

Convert to lower case
['Hello, how are you!', 'Win money, win from home.', 'Call me now.', 'Hello, Call hello you tomorrow?']
['hello, how are you!', 'win money, win from home.', 'call me now.', 'hello, call hello you tomorrow?']


In [11]:
#Satzzeichen entfernen
print("Satzzeichen entfernen")
import string
without_punktation = []
for i in lower_case_documents:
    without_punktation.append(i.translate(str.maketrans('', '', string.punctuation)))
print(without_punktation)

Satzzeichen entfernen
['hello how are you', 'win money win from home', 'call me now', 'hello call hello you tomorrow']


In [12]:
#In einzelne Woerter aufsplitten
print("In einzelne Woerter aufsplitten")
words = []
for i in without_punktation:
    words.append(i.split(' '))
print(words)

gezaehlte_Liste = []
import pprint
from collections import Counter
for i in words:
    counts = Counter(i)
    gezaehlte_Liste.append(counts)
pprint.pprint(gezaehlte_Liste)

In einzelne Woerter aufsplitten
[['hello', 'how', 'are', 'you'], ['win', 'money', 'win', 'from', 'home'], ['call', 'me', 'now'], ['hello', 'call', 'hello', 'you', 'tomorrow']]
[Counter({'hello': 1, 'are': 1, 'how': 1, 'you': 1}),
 Counter({'win': 2, 'money': 1, 'from': 1, 'home': 1}),
 Counter({'call': 1, 'me': 1, 'now': 1}),
 Counter({'hello': 2, 'you': 1, 'call': 1, 'tomorrow': 1})]


# Ab hier nutzen wir den bereits implementierten Bag of Words-Algo

In [18]:
documents = ['Hello, how are you!',
                'Win money, win from home.',
                'Call me now.',
                'Hello, Call hello you tomorrow?']
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()
print(count_vector)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)


In [21]:
count_vector.fit(documents)
count_vector.get_feature_names()

['are',
 'call',
 'from',
 'hello',
 'home',
 'how',
 'me',
 'money',
 'now',
 'tomorrow',
 'win',
 'you']

In [33]:
print("Den Vektor transformieren in eine Matrix")
print(count_vector.transform(documents))
print("und in ein Array legen")
print(count_vector.transform(documents).toarray())

Den Vektor transformieren in eine Matrix
  (0, 0)	1
  (0, 3)	1
  (0, 5)	1
  (0, 11)	1
  (1, 2)	1
  (1, 4)	1
  (1, 7)	1
  (1, 10)	2
  (2, 1)	1
  (2, 6)	1
  (2, 8)	1
  (3, 1)	1
  (3, 3)	2
  (3, 9)	1
  (3, 11)	1
und in ein Array legen
[[1 0 0 1 0 1 0 0 0 0 0 1]
 [0 0 1 0 1 0 0 1 0 0 2 0]
 [0 1 0 0 0 0 1 0 1 0 0 0]
 [0 1 0 2 0 0 0 0 0 1 0 1]]


Nun liegt in dem Array eine Matrix, die die Häufigkeiten der einzelnen Worte wiedergibt. Um es leichter lesen zu
können wandeln wir es in ein dataframe, da wir da dann auch einen beschrifteten Header haben können

In [ ]:
haefigkeits_matrix = pd.DataFrame()